// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package types

import (
	"encoding/json"
	"errors"
	"math/big"

	"github.com/Tau-Coin/taucoin-mobile-mining-go/common"
	"github.com/Tau-Coin/taucoin-mobile-mining-go/common/hexutil"
)

var _ = (*headerMarshaling)(nil)

// MarshalJSON marshals as JSON.
func (h Header) MarshalJSON() ([]byte, error) {
	type Header struct {
		ParentHash common.Hash    `json:"parentHash"       gencodec:"required"`
		Coinbase   common.Address `json:"miner"            gencodec:"required"`
		Root       common.Hash    `json:"stateRoot"        gencodec:"required"`
		TxHash     common.Hash    `json:"transactionsRoot" gencodec:"required"`
		Difficulty *hexutil.Big   `json:"difficulty"       gencodec:"required"`
		Number     *hexutil.Big   `json:"number"           gencodec:"required"`
		Time       hexutil.Uint64 `json:"timestamp"        gencodec:"required"`
		MixDigest  common.Hash    `json:"mixHash"`
		Hash       common.Hash    `json:"hash"`
	}
	var enc Header
	enc.ParentHash = h.ParentHash
	enc.Coinbase = h.Coinbase
	enc.Root = h.Root
	enc.TxHash = h.TxHash
	enc.Difficulty = (*hexutil.Big)(h.Difficulty)
	enc.Number = (*hexutil.Big)(h.Number)
	enc.Time = hexutil.Uint64(h.Time)
	enc.MixDigest = h.MixDigest
	enc.Hash = h.Hash()
	return json.Marshal(&enc)
}

// UnmarshalJSON unmarshals from JSON.
func (h *Header) UnmarshalJSON(input []byte) error {
	type Header struct {
		ParentHash *common.Hash    `json:"parentHash"       gencodec:"required"`
		Coinbase   *common.Address `json:"miner"            gencodec:"required"`
		Root       *common.Hash    `json:"stateRoot"        gencodec:"required"`
		TxHash     *common.Hash    `json:"transactionsRoot" gencodec:"required"`
		Difficulty *hexutil.Big    `json:"difficulty"       gencodec:"required"`
		Number     *hexutil.Big    `json:"number"           gencodec:"required"`
		Time       *hexutil.Uint64 `json:"timestamp"        gencodec:"required"`
		MixDigest  *common.Hash    `json:"mixHash"`
	}
	var dec Header
	if err := json.Unmarshal(input, &dec); err != nil {
		return err
	}
	if dec.ParentHash == nil {
		return errors.New("missing required field 'parentHash' for Header")
	}
	h.ParentHash = *dec.ParentHash
	if dec.Coinbase == nil {
		return errors.New("missing required field 'miner' for Header")
	}
	h.Coinbase = *dec.Coinbase
	if dec.Root == nil {
		return errors.New("missing required field 'stateRoot' for Header")
	}
	h.Root = *dec.Root
	if dec.TxHash == nil {
		return errors.New("missing required field 'transactionsRoot' for Header")
	}
	h.TxHash = *dec.TxHash
	if dec.Difficulty == nil {
		return errors.New("missing required field 'difficulty' for Header")
	}
	h.Difficulty = (*big.Int)(dec.Difficulty)
	if dec.Number == nil {
		return errors.New("missing required field 'number' for Header")
	}
	h.Number = (*big.Int)(dec.Number)
	if dec.Time == nil {
		return errors.New("missing required field 'timestamp' for Header")
	}
	h.Time = uint64(*dec.Time)
	if dec.MixDigest != nil {
		h.MixDigest = *dec.MixDigest
	}
	return nil
}
