// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package types

import (
	"encoding/json"
	"errors"
	"math/big"

	"github.com/Tau-Coin/taucoin-mobile-mining-go/common"
	"github.com/Tau-Coin/taucoin-mobile-mining-go/common/hexutil"
)

var _ = (*NewMessageTxDataMarshaling)(nil)

// MarshalJSON marshals as JSON.
func (n NewMessageTxData) MarshalJSON() ([]byte, error) {
	type NewMessageTxData struct {
		Version   hexutil.Bytes   `json:"version"     gencodec:"required"`
		Option    hexutil.Bytes   `json:"option"      gencodec:"required"`
		ChainID   hexutil.Bytes   `json:"chainid"     gencodec:"required"`
		Nonce     hexutil.Uint64  `json:"nounce"      gencodec:"required"`
		TimeStamp hexutil.Uint32  `json:"timestamp"   gencodec:"required"`
		Fee       *hexutil.Big    `json:"fee"         gencodec:"required"`
		V         *hexutil.Big    `json:"v"           gencodec:"required"`
		R         *hexutil.Big    `json:"r"           gencodec:"required"`
		S         *hexutil.Big    `json:"s"           gencodec:"required"`
		Sender    *common.Address `json:"sender"        rlp:"required"`
		Referid   *common.Hash    `json:"referid"       rlp:"-"`
		Title     hexutil.Bytes   `json:"title"         gencodec:"required"`
		Content   hexutil.Bytes   `json:"contentcid"    gencodec:"required"`
	}
	var enc NewMessageTxData
	enc.Version = hexutil.Bytes(n.Version)
	enc.Option = hexutil.Bytes(n.Option)
	enc.ChainID = hexutil.Bytes(n.ChainID)
	enc.Nonce = hexutil.Uint64(n.Nonce)
	enc.TimeStamp = hexutil.Uint32(n.TimeStamp)
	enc.Fee = (*hexutil.Big)(n.Fee)
	enc.V = (*hexutil.Big)(n.V)
	enc.R = (*hexutil.Big)(n.R)
	enc.S = (*hexutil.Big)(n.S)
	enc.Sender = n.Sender
	enc.Referid = n.Referid
	enc.Title = hexutil.Bytes(n.Title)
	enc.Content = hexutil.Bytes(n.Content)
	return json.Marshal(&enc)
}

// UnmarshalJSON unmarshals from JSON.
func (n *NewMessageTxData) UnmarshalJSON(input []byte) error {
	type NewMessageTxData struct {
		Version   *hexutil.Bytes  `json:"version"     gencodec:"required"`
		Option    *hexutil.Bytes  `json:"option"      gencodec:"required"`
		ChainID   *hexutil.Bytes  `json:"chainid"     gencodec:"required"`
		Nonce     *hexutil.Uint64 `json:"nounce"      gencodec:"required"`
		TimeStamp *hexutil.Uint32 `json:"timestamp"   gencodec:"required"`
		Fee       *hexutil.Big    `json:"fee"         gencodec:"required"`
		V         *hexutil.Big    `json:"v"           gencodec:"required"`
		R         *hexutil.Big    `json:"r"           gencodec:"required"`
		S         *hexutil.Big    `json:"s"           gencodec:"required"`
		Sender    *common.Address `json:"sender"        rlp:"required"`
		Referid   *common.Hash    `json:"referid"       rlp:"-"`
		Title     *hexutil.Bytes  `json:"title"         gencodec:"required"`
		Content   *hexutil.Bytes  `json:"contentcid"    gencodec:"required"`
	}
	var dec NewMessageTxData
	if err := json.Unmarshal(input, &dec); err != nil {
		return err
	}
	if dec.Version == nil {
		return errors.New("missing required field 'version' for NewMessageTxData")
	}
	n.Version = OneByte(*dec.Version)
	if dec.Option == nil {
		return errors.New("missing required field 'option' for NewMessageTxData")
	}
	n.Option = OneByte(*dec.Option)
	if dec.ChainID == nil {
		return errors.New("missing required field 'chainid' for NewMessageTxData")
	}
	n.ChainID = Byte32s(*dec.ChainID)
	if dec.Nonce == nil {
		return errors.New("missing required field 'nounce' for NewMessageTxData")
	}
	n.Nonce = uint64(*dec.Nonce)
	if dec.TimeStamp == nil {
		return errors.New("missing required field 'timestamp' for NewMessageTxData")
	}
	n.TimeStamp = uint32(*dec.TimeStamp)
	if dec.Fee == nil {
		return errors.New("missing required field 'fee' for NewMessageTxData")
	}
	n.Fee = (*big.Int)(dec.Fee)
	if dec.V == nil {
		return errors.New("missing required field 'v' for NewMessageTxData")
	}
	n.V = (*big.Int)(dec.V)
	if dec.R == nil {
		return errors.New("missing required field 'r' for NewMessageTxData")
	}
	n.R = (*big.Int)(dec.R)
	if dec.S == nil {
		return errors.New("missing required field 's' for NewMessageTxData")
	}
	n.S = (*big.Int)(dec.S)
	if dec.Sender != nil {
		n.Sender = dec.Sender
	}
	if dec.Referid != nil {
		n.Referid = dec.Referid
	}
	if dec.Title == nil {
		return errors.New("missing required field 'title' for NewMessageTxData")
	}
	n.Title = Byte144s(*dec.Title)
	if dec.Content == nil {
		return errors.New("missing required field 'contentcid' for NewMessageTxData")
	}
	n.Content = Byte32s(*dec.Content)
	return nil
}
